### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by nikulanton** [nikulanton/crm#1]
Потихоньку начав разбираться с новым языком появился вопрос, каким образом осуществлять "общение" фронта и бэка. В Go есть стандартная библиотека для работы с html, однако её функционала мне не достаточно. Думал над тем чтобы пересылать все данные для фронта в JSON файлах и после этого показывать их с помощью JS. С JS и фронтом я почти не работал, не могли бы вы посоветовать что-нибудь почитать или подсказать оптимальный способ.

**Comment by wldmr-key** [comment]
Навскидку я бы предложил React+Babel+Axios - то есть, ты компилишь приложение один раз, оно загружается на клиента и дальше ты обмениваешься с сервером только json (рендеринг весь на клиенте). Если приложение обладает несколько более сложной логикой, то я бы добавил сюда еще Redux
_разумеется - это не серебрянная пуля. Есть еще мильон других возможных реализаций_

**Comment by nikulanton** [comment]
Почитал о тех вещах что вы перечислили. React как по мне все таки сложноват, но благодаря гуглению о нем нашел более простую и легкую вещь - Vue. Хочу попробовать через WebSocket завязать его и свой бэк на Go c пакетом, который добавляет работу с этими самыми вебсокетами. Пока наверное попробую начать с этого.

**Comment by wldmr-key** [comment]
Vue да, неплохо
